config/routes.rb
Rails.application.routes.draw do
  root 'smile_prices#index'
  get 'about', to: "tops#index"
  get 'terms_of_use', to: "tops#terms_of_use"
  get 'privacy_policy', to: "tops#privacy_policy"
  
  resources :users, only: %i(new create show)
  resources :smile_prices
  get 'login', to: 'user_sessions#new'
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mac_menu.rb
class MacMenu < ApplicationRecord
  has_many :smileprices_macdmenus
  has_many :smile_prices, through: :smileprices_macdmenus

  scope :smileprice_and_below_menu, -> (smile_price) { where("price <= ? ", smile_price) }
  scope :random_choice, -> { order("RANDOM()") }
  scope :edamame_menu, -> { where(name: "えだまめコーン") }
  scope :poteto_menu, -> { where("name LIKE ?", "%ポテト%") }
end

app/models/smile_analysis_score.rb
class SmileAnalysisScore < ApplicationRecord
  has_one :smile_price
end

app/models/smile_price.rb
class SmilePrice < ApplicationRecord
  belongs_to :user
  belongs_to :smile_analysis_score
  has_many :smileprices_macdmenus
  has_many :mac_menus, through: :smileprices_macdmenus
end

app/models/smileprices_macdmenu.rb
class SmilepricesMacdmenu < ApplicationRecord
  belongs_to :smile_price
  belongs_to :mac_menu
end

app/models/user.rb
class User < ApplicationRecord
  has_many :smile_prices, dependent: :destroy
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name,  presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = "ログインしてください。"
    redirect_to login_path
  end

  def correct_user(resource)
    if resource.is_a?(User)
      user_to_check = resource
    else
      user_to_check = resource.user
    end
    
    unless user_to_check == current_user
      flash[:error] = "権限がありません"
      redirect_to smile_prices_path
    end
  end

end

app/controllers/smile_prices_controller.rb
class SmilePricesController < ApplicationController
  skip_before_action :require_login, only: %i[index show update]
  before_action :set_smile_price, only: %i[show edit update]
  before_action -> { correct_user(@smile_price) }, only: %i[edit update]
  before_action :chart_data, only: %i[show edit]

  def index
    @smile_prices = SmilePrice.where(is_published: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new; end

  def create
    image_data = params[:image]
    smile_price_creator = SmilePriceCreator.new(image_data, current_user)
    @smile_price_record = smile_price_creator.create_smile_price
    if @smile_price_record
      respond_to do |format|
        format.html { redirect_to edit_smile_price_path(@smile_price_record) } 
        format.json { render json: { redirect_url: edit_smile_price_path(@smile_price_record) } }
      end
    else
      respond_to do |format|
        format.html { 
          flash[:error] = "エラーが発生しました。再度お試しください。"
          redirect_to new_smile_price_path
        }
        format.json { 
          render json: { error: "エラーメッセージ" }, status: :unprocessable_entity 
        }
      end
    end
  end

  def show; end

  def edit; end

  def update
    if @smile_price.update(set_smile_price_body)
      redirect_to smile_price_path(@smile_price), success: "投稿しました。"
    else
      flash.now['danger'] = "投稿できませんでした。"
      render :edit
    end 
  end

  private

  def set_smile_price_body
    params.require(:smile_price).permit(:body, :is_published)
  end

  def set_smile_price
    @smile_price = SmilePrice.find(params[:id])
  end

  def chart_data
    return unless @smile_price.smile_analysis_score
    
    score_attributes = [
      :eye_expression_score,
      :mouth_expression_score,
      :nose_position_score,
      :jawline_score,
      :naturalness_and_balance_score
    ]

    @chart_data = score_attributes.map do |attribute|
      @smile_price.smile_analysis_score.send(attribute)
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login

  def index; end

  def privacy_policy; end

  def terms_of_use; end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to smile_prices_path, notice: 'ログインに成功しました'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end

  def guest_login
    @guest_user = User.create!(
    name: 'ゲスト',
    email: SecureRandom.alphanumeric(10) + "@email.com",
    password: 'password',
    password_confirmation: 'password'
    )
    auto_login(@guest_user)
    redirect_back_or_to smile_prices_path, notice: 'ゲストとしてログインしました'
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'ログアウトしました')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[show edit update]
  before_action -> { correct_user(@user) }, only: %i[show edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: "ユーザ登録に成功しました"
    else
      flash.now[:danger] = "ユーザ登録に失敗しました"
      render :new
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user_name
      current_user.name
    end

    def smile_analysis_score_attributes 
      {
        '目の表情' => :eye_expression_score,
        '口元の表情' => :mouth_expression_score, 
        '鼻の位置' => :nose_position_score,
        '顎の位置' => :jawline_score,
        '自然度・バランス' => :naturalness_and_balance_score,
        '総合評価' => :smile_score        
      }
    end

    def default_meta_tags
    {
      site: 'スマプラ！',
      title: 'あなたのスマイルに値段を！',
      reverse: true,
      charset: 'utf-8',
      description: 'あなたのスマイルに値段をつけて、値段にあったマックメニューを提案します！',
      keywords: 'スマイル診断,マクドナルド',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('site_logo.png'), # 配置するパスやファイル名によって変更すること
        local: 'ja-JP'
      },
      # Twitter用の設定を個別で設定する
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
        site: '@', # アプリの公式Twitterアカウントがあれば、アカウント名を書く
        image: image_url('site_logo.png') # 配置するパスやファイル名によって変更すること
      }
    }
  end

  def twitter_share_message(smile_price)
    message = "&text=【私のスマイルは#{ smile_price.price }円です!】%0a%0a【スマプラ！】であなたのスマイルに値段をつけて、値段にあったマックメニューを提案します！%0a%0a ChatGPTがあなたのスマイルを分析！%0a%0a"
    return message
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>スマプラ！</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'radar_chart', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= display_meta_tags(default_meta_tags) %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.3/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://kit.fontawesome.com/736b0ee80c.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-V2ZTX2H28M"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-V2ZTX2H28M');
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        nav {
          background-color: white;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
          font-family: "Helvetica Neue", sans-serif;
        }

        .nav-link {
        color: black;
        font-size: 16px;
        font-weight: bold;
        text-decoration: none;
        margin-right: 24px;
        transition: color 0.2s ease-in-out;
      }

      .nav-link:hover {
        color: red;
      }

      button {
        margin-right: 24px;
        font-size: 16px;
      }

      button:hover {
        cursor: pointer;
        filter: brightness(110%);
      }
    </style>
  </head>
  <body class="bg-gray-100 font-sans">
    <div class="bg-white px-4 py-5 flex justify-between items-center mb-10">
      <%= link_to 'スマプラ！', root_path, class: "text-red-500 font-bold text-2xl tracking-wider ml-5" %>
      <div>
        <% if logged_in? %>
          <%= render 'shared/header' %>
        <% else %>
          <%= render 'shared/before_login_header' %>
        <% end %>
      </div>
    </div>
    <div class="container mx-auto m-10 max-w-7xl mx-auto p-10 bg-white">
      <div class="container mx-auto">
        <div class="bg-white rounded-lg shadow-lg overflow-hidden">
            <div class="my-10">
            <%= render 'shared/flash_message' %>
            <%= yield %>
          </div>
        </div>

      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<div class="flex items-center">
  <div class="flex hidden  sm:hidden md:hidden lg:flex xl:flex">
    <div class="flex text-center m-4">
      <%= link_to 'about', about_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
      <%= link_to 'みんなのスマイル', smile_prices_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
      <%= link_to 'スマイル診断', new_smile_price_path, class: "bg-red-500 hover:bg-red-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg mr-2" %>
      <%= link_to '新規登録', new_user_path, class: "bg-yellow-500 hover:bg-yellow-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg mr-2" %>
      <%= link_to 'ログイン', login_path, class: "bg-yellow-500 hover:bg-red-500 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg" %>
    </div>
  </div>
  <div class="relative">
    <button id="MenuBar" type="button" class="mx-8 sm:flex md:flex lg:hidden xl:hidden items-center gap-x-1 text-sm font-semibold leading-6 text-gray-900" aria-expanded="false">
      <i class="fa-solid fa-bars fa-3x"></i>
    </button>

    <div id="MenuList" class="hidden absolute top-0 right-0 z-10 flex w-screen max-w-max -translate-x-1/2 px-4">
      <div class="w-screen max-w-md flex-auto overflow-hidden rounded-3xl bg-white text-sm leading-6 shadow-lg ring-1 ring-gray-900/5">
        <div class="p-4">
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <%= link_to 'about', about_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <div class="mx">
                <%= link_to 'みんなのスマイル', smile_prices_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto w-3/4 bg-red-500 hover:bg-yellow-500 rounded-3xl">
              <div class="w-full py-2 px-8 text-center">
                <%= link_to 'スマイル診断', new_smile_price_path, class: "text-white font-bold text-base text-center "  %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto w-3/4 bg-yellow-500 hover:bg-red-500 text-white rounded-full">
              <div class="w-full py-2 px-8 text-center">
                <%= link_to 'ユーザ作成', new_user_path, class: "text-white font-bold text-base text-center "  %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto w-3/4 bg-yellow-500 hover:bg-yellow-700 text-white rounded-full">
              <div class="w-full py-2 px-8 text-center">
                <%= link_to 'ログイン', login_path, class: "text-white font-bold text-base text-center "  %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <button id="MenuClose" type="button" class="inline-flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-900" aria-expanded="false">
                <i class="fas fa-window-close fa-2x"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div >
<%= javascript_pack_tag "header_menu" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error shadow-lg items-center mb-2">
    <div>
        <% object.errors.full_messages.each do |message| %>
          <span><%= message %></span>
        <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-warning shadow-lg items-center mb-2">
  <div>
    <span><%= message %></span>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-gray-900 py-8 mt-10">
  <div class="max-w-7xl mx-auto px-4">
    <div class="grid grid-cols-1 md:grid-cols-3">
      <div class="mb-8 md:mb-0">
        <h3 class="text-white text-lg font-bold mb-4">
          <%= link_to "利用規約", terms_of_use_path %>
        </h3>
      </div>
      <div class="mb-8 md:mb-0">
        <h3 class="text-white text-lg font-bold mb-4">
          <%= link_to "プライバシーポリシー", privacy_policy_path %>
        </h3>
      </div>
      <div class="mb-8 md:mb-0">
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSexLdtCIiD3NqbGEf9Zt5cTELoZtMgYM0SLqejYtJsUiv2HUw/viewform" class="text-white text-lg font-bold mb-4">お問い合わせ</a>
      </div>
    </div>
    <p class="text-gray-400 text-sm">Copyright © 2023 - All right reserved by </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="flex items-center">
  <div class="flex hidden  sm:hidden md:hidden lg:flex xl:flex">
    <div class="flex text-center m-4">
      <%= link_to 'about', about_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
      <%= link_to 'みんなのスマイル', smile_prices_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
      <%= link_to "My Page", user_path(current_user), class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
      <%= link_to 'スマイル診断', new_smile_price_path, class: "bg-red-500 hover:bg-red-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg mr-2"  %>
      <%= link_to 'ログアウト', logout_path, class: "bg-yellow-500 hover:bg-yellow-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg", method: :delete %>
    </div>
  </div>
  <div class="relative">
    <button id="MenuBar" type="button" class="mx-8 sm:flex md:flex lg:hidden xl:hidden items-center gap-x-1 text-sm font-semibold leading-6 text-gray-900" aria-expanded="false">
      <i class="fa-solid fa-bars fa-3x"></i>
    </button>

    <div id="MenuList" class="hidden absolute top-0 right-0 z-10 flex w-screen max-w-max -translate-x-1/2 px-4">
      <div class="w-screen max-w-md flex-auto overflow-hidden rounded-3xl bg-white text-sm leading-6 shadow-lg ring-1 ring-gray-900/5">
        <div class="p-4">
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <%= link_to 'about', about_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <div class="mx">
                <%= link_to 'みんなのスマイル', smile_prices_path, class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <div class="mx">
                <%= link_to "My Page", user_path(current_user), class: "text-black font-bold text-lg hover:text-red-500 transition duration-200 font-medium py-1 md:py-2 px-4 md:px-6" %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto w-3/4 bg-red-500 hover:bg-red-700 rounded-3xl">
              <div class="w-full py-2 px-8 text-center">
                <%= link_to 'スマイル診断', new_smile_price_path, class: "text-white font-bold text-base text-center "  %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto w-3/4 bg-yellow-500 hover:bg-yellow-700 text-white rounded-full">
              <div class="w-full py-2 px-8 text-center">
                <%= link_to 'ログアウト', logout_path, method: :delete, class: "text-white font-bold text-base text-center " %>
              </div>
            </div>
          </div>
          <div class="group relative flex gap-x-6 rounded-lg p-4 hover:bg-gray-50">
            <div class="mx-auto">
              <button id="MenuClose" type="button" class="inline-flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-900" aria-expanded="false">
                <i class="fas fa-window-close fa-2x"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div >
<%= javascript_pack_tag "header_menu" %>

app/views/smile_prices/_result_smileprice.html.erb
<h1 class="text-2xl text-gray-900 font-bold text-center m-10">
  <a class="text-1xl font-bold">
    <%= @smile_price.user.name %>
  </a>
  さんのスマイルは、
  <a class="text-6xl font-bold">
    <%= @smile_price.price %> 
  </a>
  円です！  
</h1>
<h2 class="text-2xl text-gray-900 font-bold text-center m-12">そのスマイルで以下のマックメニューを買おう！</h2>
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mx-2">
  <% @smile_price.mac_menus.each do |mac_menu| %>
    <div class="px-2 mb-4">
      <div class="relative h-0" style="padding-bottom: 75%">
        <%= image_tag mac_menu.image, class: 'absolute h-full w-full object-cover', id: 'preview' %>
      </div>
      <div class="px-4 py-2">
        <h3 class="text-lg font-bold text-gray-900 mb-2"><%= mac_menu.name %></h3>
        <div class="text-gray-700 font-bold"><%= mac_menu.price %>円</div>
      </div>
    </div>
  <% end %>
</div>
<% if @chart_data %>
  <h2 class="text-2xl text-gray-900 font-bold text-center m-12">ChatGPTからスマイル分析結果</h2>
  <script>
    window.chartData = <%= @chart_data.to_json.html_safe %>;
  </script>
  <div class="mx-auto aspect-ratio aspect-ratio-1/1" style="width: 100%; max-width: 700px;">
    <canvas id="myRadarChart"></canvas>
  </div>
  <div class="text-center text-gray-900 font-bold text-2xl my-4">
    <% text, attribute = smile_analysis_score_attributes.to_a.last %>
    <div class="text-gray-500 mb-1">
      <%= text %>
    </div>
    <div>
      <%= "#{@smile_price.smile_analysis_score.send(attribute)}点" %>
    </div>
  </div>
  <div class="grid grid-cols-5 gap-3 text-center text-gray-900 font-bold text-1xl mb-5">
    <% smile_analysis_score_attributes.each_with_index do |(text, attribute), index| %>
      <% if index < smile_analysis_score_attributes.length - 1 %>
        <div>
          <div class="text-gray-500 mb-1">
            <%= text %>
          </div>
          <div>
            <%= "#{@smile_price.smile_analysis_score.send(attribute)}点" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/smile_prices/edit.html.erb
<%= render "result_smileprice" %>
<%= form_with model: @smile_price, method: :patch, class: "max-w-xl rounded-lg mx-auto", local: true do |f| %>

  <div class="form-group flex items-center mt-3 mb-3">
    <%= f.check_box :is_published, class: "form-checkbox h-5 w-5 text-black border border-black bg-white mr-2" %>
    <%= f.label :is_published, '公開', class: "text-gray-900" %>
  </div>

  <%= f.label "感想投稿", class: "text-lg font-bold text-gray-900 mb-5" %>
  <%= f.text_area :body, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mb-5" %>

  <div class="flex flex-wrap justify-center gap-4">
  <a class="flex items-center justify-center bg-red-500 hover:bg-red-700 text-white rounded-full py-2 px-4 md:px-6 font-bold text-sm md:text-base w-full sm:w-auto mb-3">
    <%= f.submit "アプリ内 Share", class: "cursor-pointer" %>
  </a>
  <%= link_to "https://twitter.com/share?url=https://www.smile-price.com/#{twitter_share_message(@smile_price)}", target: '_blank', class:"flex items-center justify-center bg-blue-500 hover:bg-blue-700 text-white rounded-full py-2 px-4 md:px-6 font-bold text-sm md:text-base w-full sm:w-auto mb-3" do %>
    <i class="fab fa-twitter mr-2"></i>
    <span>Twitter Share</span>
  <% end %>
  <%= link_to "みんなのスマイル",  smile_prices_path, class: "flex items-center justify-center bg-yellow-500 hover:bg-yellow-700 text-white rounded-full py-2 px-4 md:px-6 font-bold text-sm md:text-base w-full sm:w-auto mb-3"  %>
</div>
<% end %>

app/views/user_sessions/_login_form.html.erb
<div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-5">ログイン</h2>

    <%= form_with url: login_path, method: :post, class: "max-w-lg border rounded-lg mx-auto", local: true do |f| %>
      <div class="flex flex-col gap-4 p-4 md:p-8">
        <div class="flex justify-center mb-5">
          <%= link_to "新規登録" , new_user_path, class: "bg-red-500 hover:bg-red-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg mr-4" %>
          <%= link_to 'ゲストログイン', '/guest_login', method: :post, class: "bg-yellow-500 hover:bg-yellow-700 text-white rounded-full py-1 md:py-2 px-4 md:px-6 font-bold text-base md:text-lg" %>  
        </div>
        <div>
          <%= f.label :email, class: "inline-block text-gray-800 text-sm sm:text-base mb-2" %>
          <%= f.text_field :email, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", type: 'email' %>
        </div>

        <div>
          <%= f.label :password, class: "inline-block text-gray-800 text-sm sm:text-base mb-2" %>
          <%= f.text_field :password, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2" , type: 'password' %>
        </div>
        <div class="flex justify-center">
          <a class="mt-4 px-6 py-2 bg-red-500 text-white rounded-full hover:bg-red-700 transition duration-200">
            <%= f.submit "ログイン" %>
          </a>
      </div>
    <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<%= render 'login_form' %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>